### ISSUE TITLE
Add Polkadot Mexico  (PM)

### ISSUE THREAD

**Issue by w3nerick** [galacticcouncil/intergalactic-asset-metadata#20]
### Ticker

PM

### ID

1000284

### Icon

![Sol-Solo](https://github.com/user-attachments/assets/8ad91eeb-31d3-47fe-b880-b1ded973ecd7)

**Comment by w3nerick** [comment]
![Sol-Solo](https://github.com/user-attachments/assets/36ecf85f-91b6-49b7-aeb8-a0dd6416f5b7)

**Comment by jak-pan** [comment]
PNG or SVG < 30kb... > 128x128 no need for bigger image.

**Comment by w3nerick** [comment]
![file](https://github.com/user-attachments/assets/ff6cbd77-56c4-4a95-be99-42c51f31165b)
