### ISSUE TITLE
Add Million (Mill)

### ISSUE THREAD

**Issue by caybach** [galacticcouncil/intergalactic-asset-metadata#60]
### Ticker

Mill

### ID

1000453

### Icon SVG or PNG < 30kb 128x128

![1 M copy](https://github.com/user-attachments/assets/b535f605-6ad8-40e6-a0ff-dd77986f7197)

**Comment by vkulinich-cl** [comment]
@caybach update your icon, please. Otherwise, it will be cropped, when rounded 
![361176400-b535f605-6ad8-40e6-a0ff-dd77986f7197 (1)-modified](https://github.com/user-attachments/assets/1eaac531-feb1-48db-96b6-a0b56d24a9ff)

**Comment by caybach** [comment]
![1 M copy](https://github.com/user-attachments/assets/953993d0-6fc3-424a-ae55-0cfcaf23215f)
Thank you!
