### ISSUE TITLE
Add Kaibyō (Kaibyō)

### ISSUE THREAD

**Issue by cobramikeplayer** [galacticcouncil/intergalactic-asset-metadata#63]
### Ticker

Kaibyō

### ID

1000473

### Icon SVG or PNG < 30kb 128x128

Im so sorry, The ticker isnt showing properly. I think the ō did not take in the burn of the token or isnt being read, its just the ox... Can you change the ticker to KAIBYO? or do i have to go to another place?

![KAIBYO 1](https://github.com/user-attachments/assets/adb77f5f-cf29-418f-af83-9d4cf8865d9c)

**Comment by cobramikeplayer** [comment]
Sorry didnt realise this was already take on Sol. That might be the issue with the name coming up as a 0x4b61696279c58d.

**Comment by jvonasek** [comment]
we were able to display correct name

**Comment by cobramikeplayer** [comment]
I'm struggling to find the coin now. I had it either in asset hub or in
another account derivative. It's not showing in subscan under Kaibyo or
anything close. I do have the wallet address it was transferred to so
hopefully this works and I can get this back up.

**Comment by cobramikeplayer** [comment]
I'm good now found Kaibyo... Thanks so much!

**Comment by cobramikeplayer** [comment]
Unfortunately when the name was corrected the assest Kaibyō was unpegged in asstes hub. The result of the name change was the tokens being burnt to zero.  I appologize. I now know not to do that.  There is now a new KAIBYO minted with a new add token request. Please remove this version of the token, Kaibyō (Kaibyō) #63.
![Kaibyō burnt tokens Subscan_Hydration_asstess_pg2](https://github.com/user-attachments/assets/71a63498-841f-41c9-bb8c-12b778fee426)

**Comment by cobramikeplayer** [comment]
![Kaibyō burnt tokens Assethub_Hydration_crosschain_zero_balance](https://github.com/user-attachments/assets/f4ad7c01-e865-444f-82d6-ba233f43b595)

**Comment by cobramikeplayer** [comment]
![Screenshot 2024-09-05 215808](https://github.com/user-attachments/assets/4fffb9e1-4964-4a6b-914b-540a9dcd917b)
The issue is now fixed.
