### ISSUE TITLE
Add Homosapien Sapien (SAPIEN)

### ISSUE THREAD

**Issue by cobramikeplayer** [galacticcouncil/intergalactic-asset-metadata#67]
### Ticker

SAPIEN

### ID

1000492

### Icon SVG or PNG < 30kb 128x128

![Homosapien Sapien](https://github.com/user-attachments/assets/7d6d7752-2b0a-4a0f-893a-14a8679fefda)

**Comment by cobramikeplayer** [comment]
Please if posible, can you change the token name registared on Hydration from Homosapien Sapien to Sapien Sapien.  No change to the ticker.

Here is a few extra images.
![Homosapien Sapien](https://github.com/user-attachments/assets/8ecbd262-1763-4c3e-8789-a2fbf80e4e2b)

![Homosapien Sapien](https://github.com/user-attachments/assets/70b7ea38-278b-4717-aac2-a4533dd11f15)

**Comment by jvonasek** [comment]
Hi, its not possible to change the name

**Comment by cobramikeplayer** [comment]
Ok, no problem.

**Comment by cobramikeplayer** [comment]
I closed the issue and changed the name back.
