### ISSUE TITLE
Add Sophia (SOPHIA)

### ISSUE THREAD

**Issue by cobramikeplayer** [galacticcouncil/intergalactic-asset-metadata#71]
### Ticker

SOPHIA

### ID

1000524

### Icon SVG or PNG < 30kb 128x128

![Sophia 2](https://github.com/user-attachments/assets/0385dc79-e181-4c02-a38f-77de3276cce6)

![Sophia 2](https://github.com/user-attachments/assets/3714a739-da83-4435-9cbf-4edc86e4554d)

**Comment by cobramikeplayer** [comment]
![Sophia 1](https://github.com/user-attachments/assets/86b22987-b599-4749-8e29-3d3a531b1cf0)

![Sophia 1](https://github.com/user-attachments/assets/a3f17e28-6278-4614-8b9e-a55357631f5f)

**Comment by jvonasek** [comment]
added
