### ISSUE TITLE
Add Biff (BIFF)

### ISSUE THREAD

**Issue by cobramikeplayer** [galacticcouncil/intergalactic-asset-metadata#73]
### Ticker

BIFF

### ID

1000530

### Icon SVG or PNG < 30kb 128x128

![Biff 2](https://github.com/user-attachments/assets/6561ff9f-e768-4cf8-9dc8-e31f4df40e8c)

![Biff 2](https://github.com/user-attachments/assets/411308c3-53a1-4794-ae21-6ab93376e08e)

**Comment by jvonasek** [comment]
added
