### ISSUE TITLE
Add H@SH

### ISSUE THREAD

**Issue by cobramikeplayer** [galacticcouncil/intergalactic-asset-metadata#75]
### Ticker

H@SH

### ID

1000331

### Icon SVG or PNG < 30kb 128x128

The icon picture disapeared in Hydration, I am not able to see it. However H@sh image works on assethub cross chain to Hydration.

![block has 5](https://github.com/user-attachments/assets/45678fba-bb00-4989-8999-7ac9ea442b16)

If Hydration or Subscan not approved please change to 

![block_h@sh_v2 1](https://github.com/user-attachments/assets/45643fab-a302-4808-a702-20361472ca56)

**Comment by cobramikeplayer** [comment]
![Error Icon mix up H@SH with Free Kim com](https://github.com/user-attachments/assets/b24a4c8a-a35c-4735-98fc-6fcbf925f31e)

**Comment by cobramikeplayer** [comment]
Looks like the oringal was migrated to the wrong token on hydration.

**Comment by jvonasek** [comment]
> Looks like the oringal was migrated to the wrong token on hydration.

this has been fixed
