### ISSUE TITLE
Add KUSAMAOBAMAYOMAMA (KOYM)

### ISSUE THREAD

**Issue by moridin-eth** [galacticcouncil/intergalactic-asset-metadata#82]
### Ticker

KOYM

### ID

1000550

### Icon SVG or PNG < 30kb 128x128

![Gemini_Generated_Image_ui51jhui51jhui51](https://github.com/user-attachments/assets/6cb797d3-c03d-4f91-9d70-52db973ea024)

**Comment by jvonasek** [comment]
added
